openapi: '3.0.1'
info:
  title: Quiz
  version: '1.0'
  description: Small Quiz Api
servers:
  - url: http://localhost:3000
    description: local
paths:
  /users/register:
    post:
      operationId: createAccount
      description: Create an account
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        201:
          description: User created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
  /quizzes/{quizId}:
    put:
      operationId: editQuiz
      description: Edit a quiz
      security:
        - basicAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/QuizTemplate"
      responses:
        401:
          $ref: "#/components/responses/UnauthorizedError"
        200:
          description: Quiz updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/QuizTemplate"
  /quizzes:
    post:
      operationId: createQuiz
      description: Create a quiz
      security:
        - basicAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/QuizTemplate"
      responses:
        401:
          $ref: "#/components/responses/UnauthorizedError"
        201:
          description: Quiz created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/QuizTemplate"

components:
  responses:
    UnauthorizedError:
      description: Authentication information is missing or invalid
      headers:
        WWW_Authenticate:
          schema:
            type: string
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
  schemas:
    Answer:
      type: object
      properties:
        text:
          type: string
          example: 42
        isCorrect:
          type: boolean
          example: true
    QuestionTemplate:
      type: object
      properties:
        questionText:
          type: string
          example: what is the answer to life the universe and everything
        questionScore:
          type: integer
          example: 5
        answers:
          type: array
          items:
            $ref: "#/components/schemas/Answer"
    QuizTemplate:
      type: object
      properties:
        questions:
          type: array
          minItems: 1
          items:
            $ref: "#/components/schemas/QuestionTemplate"
    Token:
      type: string
      example: Basic ZGVtbzpwQDU1dzByZA==
    User:
      type: object
      properties:
        login:
          type: string
          example: laura
        password:
          type: string
          example: mypassword

