/**
 * Quiz
 * Small Quiz Api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { QuizSubmissionResult } from './quizSubmissionResult.model';


export interface QuizStatistics { 
    quizId?: string;
    totalSubmissions: number;
    submissionsStat: QuizSubmissionResult[]
}

